In [1]:
import numpy as np

In [3]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
array.max()

10

In [10]:
array.min()

1

In [11]:
array.mean()

5.5

In [17]:
array * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [21]:
np.unique(np.array([1,1,1,1,1,1,1,1,1,1]))

array([1])

In [26]:
np.array([2,3]) * np.array([7,8])

array([14, 24])

In [27]:
np.array(np.mat('1 2; 3 4'), subok=True)

matrix([[1, 2],
        [3, 4]])

In [29]:
np.mat('1 2; 3 4') * 4

matrix([[ 4,  8],
        [12, 16]])

In [32]:
np.mat('1 2; 3 4') * np.mat('5; 3')

matrix([[11],
        [27]])

In [33]:
np.mat('1 2; 3 4') * np.mat('5 1; 3 4')

matrix([[11,  9],
        [27, 19]])

In [5]:
mat = np.random.randn(100, 4)
mat.shape

(100, 4)

In [15]:
mat

array([[-4.75841631e-01, -4.13908362e-02, -1.76229472e-01,
         2.49060333e-01],
       [-4.72918918e-01, -1.22008447e+00,  4.91144691e-02,
         3.39932837e-01],
       [ 4.42639408e-01, -9.52532605e-02, -3.43657464e-01,
         8.78266576e-01],
       [ 3.48559590e-01, -3.59089995e-01,  1.52523317e+00,
        -1.04938443e+00],
       [ 1.92758039e+00, -1.10913508e+00,  3.02490883e-01,
        -9.80636518e-01],
       [ 1.81494241e+00,  1.01485900e+00,  1.51998446e+00,
         1.06743188e+00],
       [-1.15563231e-02,  9.53775542e-01, -6.77211830e-01,
        -2.17031223e-01],
       [ 3.19755411e-01,  2.37570618e-01, -1.20487594e+00,
        -1.35564977e+00],
       [ 3.89745520e-01,  8.74448753e-02, -7.89298140e-01,
         1.45360416e+00],
       [ 3.26875893e-01, -2.62583842e+00, -7.41378113e-01,
        -1.38161206e+00],
       [ 6.67757130e-01,  1.28006877e-01, -1.49155915e-01,
         5.03228453e-01],
       [-4.71613170e-01,  1.35923098e+00,  8.30785454e-02,
      

In [17]:
def fatorial(x):
    return np.prod(np.array(range(1,x+1)))

fatorial(5)

120